### ISSUE TITLE
Score if hyp==ref

### ISSUE THREAD

**Issue by jheinecke** [neulab/BARTScore#11]
I'm not sure whether I have not understood you paper correctly or if your code has a bug. What is the score to expect if the sentence in ref and hyp is nearly or totally identical

in

```
a = "This is a very good meal."
bart_scorer.score([a], [a], batch_size=4)
[-0.40471726655960083]
```
and 
```
a = "This is a good meal ."
bart_scorer.score([a], [a], batch_size=4)
[-0.4944288432598114]
```

reference and hypothesis are identical, nevertheless the score is below 0. For identical sentences I would expect 0. 
With shorter (identical) sentences, the score even gets worse, with (much) longer it improves, but does not reach 0.
So where is my error ? :-)

**Comment by neubig** [comment]
BARTScore is defined as the negative log likelihood of generating the output given the input. The only way the score would be 0 for identical sentences is if all the probability mass was assigned to the identical sentence, which means there would be no probability mass left for the other sentences. So basically, this negative score for identical sentences is expected behavior. But you might expect that this score will be a rough upper bound (it is unlikely, but not impossible that other outputs will get a higher score).
