### ISSUE TITLE
hello, is this metric the lower the better? and I wonder Why the value is negative?

### ISSUE THREAD

**Issue by meiling-fdu** [neulab/BARTScore#35]

**Comment by UntotaufUrlaub** [comment]
I think this can be closed, as the answer is provided in the Readme.

"Since we are using the average log-likelihood for target tokens, the calculated scores will be smaller than 0 (the probability is between 0 and 1, so the log of it should be negative). The higher the log-likelihood, the higher the probability.

To give an example, if SummaryA gets a score of -1 while SummaryB gets a score of -100, this means that the model thinks SummaryA is better than summaryB."

So, the higher the better, and negative because it's the log of the prob.
